services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Controller Argument
    Movioza\Attribute\ControllerArgument\:
        resource: '%kernel.project_dir%/src/Attribute/ControllerArgument/*Handler.php'
        tags:
            - { name: movioza.controller.argument_attribute_handler }

    Movioza\Resolver\AttributeValueResolver:
        tags:
            - { name: controller.argument_value_resolver }

    movioza.attribute.controller_argument.handler_registry:
        class: Movioza\Attribute\ControllerArgument\HandlerRegistry

    Movioza\Attribute\ControllerArgument\HandlerRegistryInterface: '@movioza.attribute.controller_argument.handler_registry'

    # Controller
    Movioza\Attribute\Controller\:
        resource: '%kernel.project_dir%/src/Attribute/Controller/*Handler.php'
        tags:
            - { name: movioza.controller.attribute_handler }

    movioza.attribute.controller.handler_registry:
        class: Movioza\Attribute\Controller\HandlerRegistry

    Movioza\Attribute\Controller\HandlerRegistryInterface: '@movioza.attribute.controller.handler_registry'
