services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Genre
    movioza.factory.genre:
        class: Movioza\Factory\GenreFactory

    Movioza\Factory\Interfaces\GenreFactoryInterface: '@movioza.factory.genre'

    # Person
    movioza.factory.person:
        class: Movioza\Factory\PersonFactory

    Movioza\Factory\Interfaces\PersonFactoryInterface: '@movioza.factory.person'

    # Media
    movioza.factory.media:
        class: Movioza\Factory\MediaFactory

    Movioza\Factory\Interfaces\MediaFactoryInterface: '@movioza.factory.media'

    # Media Source
    movioza.factory.media_source:
        class: Movioza\Factory\MediaSourceFactory

    Movioza\Factory\Interfaces\MediaSourceFactoryInterface: '@movioza.factory.media_source'

    # Outbox Message
    movioza.factory.outbox_message:
        class: Movioza\Factory\OutboxMessageFactory

    Movioza\Factory\Interfaces\OutboxMessageFactoryInterface: '@movioza.factory.outbox_message'
