services:
    _defaults:
        autowire: true
        autoconfigure: true

    Movioza\Repository\:
        resource: '%kernel.project_dir%/src/Repository/*Repository.php'

    # Country
    movioza.repository.country:
        class: Movioza\Repository\CountryRepository

    Movioza\Repository\Interfaces\CountryRepositoryInterface: '@movioza.repository.country'

    # Genre
    movioza.repository.genre:
        class: Movioza\Repository\GenreRepository

    Movioza\Repository\Interfaces\GenreRepositoryInterface: '@movioza.repository.genre'

    # Media
    movoiza.repository.media:
        class: Movioza\Repository\MediaRepository

    Movioza\Repository\Interfaces\MediaRepositoryInterface: '@movoiza.repository.media'

    # Media Source
    movioza.repository.media_source:
        class: Movioza\Repository\MediaSourceRepository

    Movioza\Repository\Interfaces\MediaSourceRepositoryInterface: '@movioza.repository.media_source'

    # Outbox Message
    movioza.repository.outbox_message:
        class: Movioza\Repository\OutboxMessageRepository

    Movioza\Repository\Interfaces\OutboxMessageRepositoryInterface: '@movioza.repository.outbox_message'
