services:
    _defaults:
        autowire: true
        autoconfigure: true

    Movioza\Shared\Presentation\Console\:
        resource: '%kernel.project_dir%/src/Shared/Presentation/Console/*'

    # Outbox
    movioza.outbox.repository.doctrine:
        class: Movioza\Shared\Infrastructure\Doctrine\Repository\DoctrineOutboxMessageRepository

    Movioza\Shared\Domain\Outbox\OutboxMessageRepositoryInterface: '@movioza.outbox.repository.doctrine'

    movioza.outbox.serializer.symfony:
        class: Movioza\Shared\Infrastructure\Outbox\SymfonyOutboxCommandSerializer

    Movioza\Shared\Application\Outbox\OutboxCommandSerializerInterface: '@movioza.outbox.serializer.symfony'

    movioza.outbox.bus.doctrine:
        class: Movioza\Shared\Infrastructure\Bus\Command\DoctrineOutboxCommandBus

    Movioza\Shared\Application\Bus\Command\OutboxCommandBusInterface: '@movioza.outbox.bus.doctrine'

    # Inbox
    movioza.inbox.repository.doctrine:
        class: Movioza\Shared\Infrastructure\Doctrine\Repository\DoctrineInboxMessageRepository

    Movioza\Shared\Domain\Inbox\InboxMessageRepositoryInterface: '@movioza.inbox.repository.doctrine'

    # Command
    movioza.command.bus.symfony:
        class: Movioza\Shared\Infrastructure\Bus\Command\SymfonyCommandBus

    Movioza\Shared\Application\Bus\Command\CommandBusInterface: '@movioza.command.bus.symfony'

    # Messenger
    movioza.messenger.middleware.idempotency:
        class: Movioza\Shared\Infrastructure\Messenger\Middleware\IdempotencyMiddleware

    # UUID
    movioza.uuid.generator.symfony:
        class: Movioza\Shared\Infrastructure\Uuid\SymfonyUuidGenerator

    Movioza\Shared\Domain\Uuid\UuidGeneratorInterface: '@movioza.uuid.generator.symfony'
