services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Event Listeners
    Movioza\Shared\Infrastructure\Symfony\EventListener\:
        resource: '%kernel.project_dir%/src/Shared/Infrastructure/Symfony/EventListener/*'


    # Attribute Argument Value Resolver
    Movioza\Shared\Infrastructure\Symfony\Resolver\AttributeValueResolver:
        tags:
            - { name: controller.argument_value_resolver }

    # Controller Argument Attribute Handlers
    Movioza\Shared\Infrastructure\Symfony\Attribute\ControllerArgument\:
        resource: '%kernel.project_dir%/src/Shared/Infrastructure/Symfony/Attribute/ControllerArgument/*Handler.php'
        tags:
            - { name: movioza.controller_argument_attribute.handler }

    # Controller Argument Attribute Handlers Registry
    movioza.controller_argument_attribute.registry:
        class: Movioza\Shared\Infrastructure\Symfony\Attribute\ControllerArgument\HandlerRegistry
        arguments:
            $handlers: !tagged_iterator movioza.controller_argument_attribute.handler

    Movioza\Shared\Infrastructure\Symfony\Attribute\ControllerArgument\HandlerRegistryInterface: '@movioza.controller_argument_attribute.registry'

    # Controller Attribute Handlers
    Movioza\Shared\Infrastructure\Symfony\Attribute\Controller\:
        resource: '%kernel.project_dir%/src/Shared/Infrastructure/Symfony/Attribute/Controller/*Handler.php'
        tags:
            - { name: movioza.controller_attribute.handler }

    # Controller Attribute Handlers Registry
    movioza.controller_attribute.registry:
        class: Movioza\Shared\Infrastructure\Symfony\Attribute\Controller\HandlerRegistry
        arguments:
            $handlers: !tagged_iterator movioza.controller_attribute.handler

    Movioza\Shared\Infrastructure\Symfony\Attribute\Controller\HandlerRegistryInterface: '@movioza.controller_attribute.registry'

    # Slug
    movioza.slug_generator.cocur:
        class: Movioza\Shared\Infrastructure\Slug\CocurSlugGenerator

    Movioza\Shared\Domain\SlugGeneratorInterface: '@movioza.slug_generator.cocur'

    # Downloader
    movioza.downloader.aria2:
        class: Movioza\Shared\Infrastructure\Aria2\Aria2Downloader
        
    Movioza\Shared\Domain\Downloader\DownloaderInterface: '@movioza.downloader.aria2'
