doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            shared_country_id: Movioza\Shared\Infrastructure\Doctrine\Type\CountryIDType
            shared_country_name: Movioza\Shared\Infrastructure\Doctrine\Type\CountryNameType
            shared_country_code: Movioza\Shared\Infrastructure\Doctrine\Type\CountryCodeType
            assets_file_id: Movioza\Shared\Infrastructure\Doctrine\Type\FileIDType
            assets_image_id: Movioza\Shared\Infrastructure\Doctrine\Type\ImageIDType
            assets_storage_bucket: Movioza\Shared\Infrastructure\Doctrine\Type\StorageBucketType
            assets_storage_key: Movioza\Shared\Infrastructure\Doctrine\Type\StorageKeyType
            assets_blur_hash: Movioza\Shared\Infrastructure\Doctrine\Type\BlurHashType
            assets_file_extension: Movioza\Shared\Infrastructure\Doctrine\Type\FileExtensionType
            assets_file_size: Movioza\Shared\Infrastructure\Doctrine\Type\FileSize

    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            Shared:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mapping'
                prefix: Movioza\Shared\Domain
                alias: Shared
            Assets:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Assets/Infrastructure/Doctrine/Mapping'
                prefix: Movioza\Assets\Domain
                alias: Assets

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
