<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260530211852 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE countries (name VARCHAR(120) NOT NULL, code VARCHAR(3) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D66EBAD5E237E06 ON countries (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D66EBAD77153098 ON countries (code)');
        $this->addSql('CREATE TABLE episode_images (type VARCHAR(32) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, episode_id BIGINT NOT NULL, image_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C222171362B62A0 ON episode_images (episode_id)');
        $this->addSql('CREATE INDEX IDX_8C2221713DA5256D ON episode_images (image_id)');
        $this->addSql('CREATE TABLE episodes (title VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, season_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7DD55EDD4EC001D1 ON episodes (season_id)');
        $this->addSql('CREATE TABLE files (storage VARCHAR(32) NOT NULL, bucket VARCHAR(255) NOT NULL, key VARCHAR(1024) NOT NULL, extension VARCHAR(16) NOT NULL, size BIGINT NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_63540598A90ABA9 ON files (key)');
        $this->addSql('CREATE TABLE genres (name VARCHAR(80) NOT NULL, slug VARCHAR(120) NOT NULL, emoji VARCHAR(16) NOT NULL, short_description VARCHAR(80) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A8EBE5165E237E06 ON genres (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A8EBE516989D9B62 ON genres (slug)');
        $this->addSql('CREATE TABLE images (width INT NOT NULL, height INT NOT NULL, blur_hash VARCHAR(255) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E01FBE6A93CB796C ON images (file_id)');
        $this->addSql('CREATE TABLE media (type VARCHAR(32) NOT NULL, kind VARCHAR(32) DEFAULT NULL, title VARCHAR(255) NOT NULL, alternative_titles JSON NOT NULL, slug VARCHAR(280) NOT NULL, description TEXT NOT NULL, age_restrictions INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON COLUMN media.uploaded_at IS \'Assigned after the first video file is loaded and remains unchangeable.\'');
        $this->addSql('COMMENT ON COLUMN media.released_at IS \'Date of media content release worldwide\'');
        $this->addSql('CREATE TABLE media_countries (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_id BIGINT NOT NULL, country_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78065823EA9FDD75 ON media_countries (media_id)');
        $this->addSql('CREATE INDEX IDX_78065823F92F3E70 ON media_countries (country_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_media_country_media_country ON media_countries (media_id, country_id)');
        $this->addSql('CREATE TABLE media_images (type VARCHAR(32) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_id BIGINT NOT NULL, image_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C6624B4EA9FDD75 ON media_images (media_id)');
        $this->addSql('CREATE INDEX IDX_5C6624B43DA5256D ON media_images (image_id)');
        $this->addSql('CREATE TABLE media_persons (role VARCHAR(32) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_id BIGINT NOT NULL, person_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C38B419AEA9FDD75 ON media_persons (media_id)');
        $this->addSql('CREATE INDEX IDX_C38B419A217BBB47 ON media_persons (person_id)');
        $this->addSql('CREATE TABLE person_images (type VARCHAR(32) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, person_id BIGINT NOT NULL, image_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CBA8EDC217BBB47 ON person_images (person_id)');
        $this->addSql('CREATE INDEX IDX_7CBA8EDC3DA5256D ON person_images (image_id)');
        $this->addSql('CREATE TABLE persons (name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, biography TEXT DEFAULT NULL, gender VARCHAR(32) DEFAULT NULL, birth_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE season_images (type VARCHAR(32) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, season_id BIGINT NOT NULL, image_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F66440D84EC001D1 ON season_images (season_id)');
        $this->addSql('CREATE INDEX IDX_F66440D83DA5256D ON season_images (image_id)');
        $this->addSql('CREATE TABLE seasons (title VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B4F4301CEA9FDD75 ON seasons (media_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_seasons_media_id_title ON seasons (media_id, title)');
        $this->addSql('COMMENT ON COLUMN seasons.released_at IS \'Worldwide release date\'');
        $this->addSql('ALTER TABLE episode_images ADD CONSTRAINT FK_8C222171362B62A0 FOREIGN KEY (episode_id) REFERENCES episodes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE episode_images ADD CONSTRAINT FK_8C2221713DA5256D FOREIGN KEY (image_id) REFERENCES images (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE episodes ADD CONSTRAINT FK_7DD55EDD4EC001D1 FOREIGN KEY (season_id) REFERENCES seasons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE images ADD CONSTRAINT FK_E01FBE6A93CB796C FOREIGN KEY (file_id) REFERENCES files (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_countries ADD CONSTRAINT FK_78065823EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_countries ADD CONSTRAINT FK_78065823F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_images ADD CONSTRAINT FK_5C6624B4EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_images ADD CONSTRAINT FK_5C6624B43DA5256D FOREIGN KEY (image_id) REFERENCES images (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_persons ADD CONSTRAINT FK_C38B419AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_persons ADD CONSTRAINT FK_C38B419A217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person_images ADD CONSTRAINT FK_7CBA8EDC217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person_images ADD CONSTRAINT FK_7CBA8EDC3DA5256D FOREIGN KEY (image_id) REFERENCES images (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE season_images ADD CONSTRAINT FK_F66440D84EC001D1 FOREIGN KEY (season_id) REFERENCES seasons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE season_images ADD CONSTRAINT FK_F66440D83DA5256D FOREIGN KEY (image_id) REFERENCES images (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seasons ADD CONSTRAINT FK_B4F4301CEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE episode_images DROP CONSTRAINT FK_8C222171362B62A0');
        $this->addSql('ALTER TABLE episode_images DROP CONSTRAINT FK_8C2221713DA5256D');
        $this->addSql('ALTER TABLE episodes DROP CONSTRAINT FK_7DD55EDD4EC001D1');
        $this->addSql('ALTER TABLE images DROP CONSTRAINT FK_E01FBE6A93CB796C');
        $this->addSql('ALTER TABLE media_countries DROP CONSTRAINT FK_78065823EA9FDD75');
        $this->addSql('ALTER TABLE media_countries DROP CONSTRAINT FK_78065823F92F3E70');
        $this->addSql('ALTER TABLE media_images DROP CONSTRAINT FK_5C6624B4EA9FDD75');
        $this->addSql('ALTER TABLE media_images DROP CONSTRAINT FK_5C6624B43DA5256D');
        $this->addSql('ALTER TABLE media_persons DROP CONSTRAINT FK_C38B419AEA9FDD75');
        $this->addSql('ALTER TABLE media_persons DROP CONSTRAINT FK_C38B419A217BBB47');
        $this->addSql('ALTER TABLE person_images DROP CONSTRAINT FK_7CBA8EDC217BBB47');
        $this->addSql('ALTER TABLE person_images DROP CONSTRAINT FK_7CBA8EDC3DA5256D');
        $this->addSql('ALTER TABLE season_images DROP CONSTRAINT FK_F66440D84EC001D1');
        $this->addSql('ALTER TABLE season_images DROP CONSTRAINT FK_F66440D83DA5256D');
        $this->addSql('ALTER TABLE seasons DROP CONSTRAINT FK_B4F4301CEA9FDD75');
        $this->addSql('DROP TABLE countries');
        $this->addSql('DROP TABLE episode_images');
        $this->addSql('DROP TABLE episodes');
        $this->addSql('DROP TABLE files');
        $this->addSql('DROP TABLE genres');
        $this->addSql('DROP TABLE images');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE media_countries');
        $this->addSql('DROP TABLE media_images');
        $this->addSql('DROP TABLE media_persons');
        $this->addSql('DROP TABLE person_images');
        $this->addSql('DROP TABLE persons');
        $this->addSql('DROP TABLE season_images');
        $this->addSql('DROP TABLE seasons');
    }
}
