<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603224048 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_sources (torrent_tracker_url VARCHAR(2048) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_id BIGINT NOT NULL, season_id BIGINT DEFAULT NULL, episode_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B38AE3BBEA9FDD75 ON media_sources (media_id)');
        $this->addSql('CREATE INDEX IDX_B38AE3BB4EC001D1 ON media_sources (season_id)');
        $this->addSql('CREATE INDEX IDX_B38AE3BB362B62A0 ON media_sources (episode_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_media_sources_media_id_torrent_tracker_url ON media_sources (media_id, torrent_tracker_url)');
        $this->addSql('ALTER TABLE media_sources ADD CONSTRAINT FK_B38AE3BBEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_sources ADD CONSTRAINT FK_B38AE3BB4EC001D1 FOREIGN KEY (season_id) REFERENCES seasons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_sources ADD CONSTRAINT FK_B38AE3BB362B62A0 FOREIGN KEY (episode_id) REFERENCES episodes (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media_sources DROP CONSTRAINT FK_B38AE3BBEA9FDD75');
        $this->addSql('ALTER TABLE media_sources DROP CONSTRAINT FK_B38AE3BB4EC001D1');
        $this->addSql('ALTER TABLE media_sources DROP CONSTRAINT FK_B38AE3BB362B62A0');
        $this->addSql('DROP TABLE media_sources');
    }
}
