<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260605225019 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_source_artifacts (type VARCHAR(32) NOT NULL, value VARCHAR(2048) NOT NULL, status VARCHAR(32) NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_source_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA90D73B05CAFEF ON media_source_artifacts (media_source_id)');
        $this->addSql('ALTER TABLE media_source_artifacts ADD CONSTRAINT FK_BA90D73B05CAFEF FOREIGN KEY (media_source_id) REFERENCES media_sources (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE episodes ADD number INT NOT NULL');
        $this->addSql('ALTER TABLE media_sources ADD status VARCHAR(32) NOT NULL');
        $this->addSql('ALTER TABLE seasons ADD number INT NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media_source_artifacts DROP CONSTRAINT FK_BA90D73B05CAFEF');
        $this->addSql('DROP TABLE media_source_artifacts');
        $this->addSql('ALTER TABLE episodes DROP number');
        $this->addSql('ALTER TABLE media_sources DROP status');
        $this->addSql('ALTER TABLE seasons DROP number');
    }
}
