<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260531210649 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media__genres (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_id BIGINT NOT NULL, genre_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_300F84DCEA9FDD75 ON media__genres (media_id)');
        $this->addSql('CREATE INDEX IDX_300F84DC4296D31F ON media__genres (genre_id)');
        $this->addSql('ALTER TABLE media__genres ADD CONSTRAINT FK_300F84DCEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media__genres ADD CONSTRAINT FK_300F84DC4296D31F FOREIGN KEY (genre_id) REFERENCES genres (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media__genres DROP CONSTRAINT FK_300F84DCEA9FDD75');
        $this->addSql('ALTER TABLE media__genres DROP CONSTRAINT FK_300F84DC4296D31F');
        $this->addSql('DROP TABLE media__genres');
    }
}
