imports:
    - { resource: './services/attribute.yaml' }
    - { resource: './services/serializer.yaml' }
    - { resource: './services/factory.yaml' }
    - { resource: './services/repository.yaml' }

parameters: []

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Movioza\Controller\:
        resource: '%kernel.project_dir%/src/Controller/**/*Controller.php'
        tags:
            - { name: controller.service_arguments }

    Movioza\EventListener\:
        resource: '%kernel.project_dir%/src/EventListener/*'

    # Slug generator
    movioza.slug_generator.cocur:
        class: Movioza\Service\Slug\CocurSlugGenerator

    Movioza\Service\Slug\SlugGeneratorInterface: '@movioza.slug_generator.cocur'
