imports:
    - { resource: './services/attribute.yaml' }
    - { resource: './services/serializer.yaml' }

parameters: []

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Movioza\Controller\:
        resource: '%kernel.project_dir%/src/Controller/**/*Controller.php'
        tags:
            - { name: controller.service_arguments }


