imports:
    - { resource: './services/attribute.yaml' }
    - { resource: './services/serializer.yaml' }
    - { resource: './services/factory.yaml' }
    - { resource: './services/repository.yaml' }
    - { resource: './services/api.yaml' }
    - { resource: './services/cdn.yaml' }

parameters: []

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Movioza\Controller\:
        resource: '%kernel.project_dir%/src/Controller/**/*Controller.php'
        tags:
            - { name: controller.service_arguments }

    Movioza\DataFixtures\:
        resource: '%kernel.project_dir%/src/DataFixtures/*Fixtures.php'

    Movioza\EventListener\:
        resource: '%kernel.project_dir%/src/EventListener/*'

    # Redis
    movioza.redis.client:
        class: Predis\Client
        arguments:
            - {
                scheme: '%env(REDIS_SCHEME)%',
                host: '%env(REDIS_HOST)%',
                port: '%env(REDIS_PORT)%',
                password: '%env(REDIS_PASSWORD)%',
                database: '%env(REDIS_DATABASE)%',
                read_write_timeout: -1
            }

    Predis\ClientInterface: '@movioza.redis.client'

    # AWS
    movioza.s3.client:
        class: Aws\S3\S3Client
        arguments:
            -   version: '%env(S3_VERSION)%'
                region: '%env(S3_REGION)%'
                endpoint: '%env(S3_ENDPOINT)%'
                use_path_style_endpoint: '%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%'
                credentials:
                    key: '%env(S3_ACCESS_KEY)%'
                    secret: '%env(S3_SECRET_KEY)%'

    Aws\S3\S3ClientInterface: '@movioza.s3.client'

    # Aria2
    movioza.aria2.client:
        class: Movioza\Service\Aria2\Aria2Client
        arguments:
            $host: '%env(ARIA2_HOST)%'
            $port: '%env(ARIA2_PORT)%'
            $secret: '%env(ARIA2_SECRET)%'

    Movioza\Service\Aria2\Aria2ClientInterface: '@movioza.aria2.client'

    # Slug generator
    movioza.slug_generator.cocur:
        class: Movioza\Service\Slug\CocurSlugGenerator

    Movioza\Service\Slug\SlugGeneratorInterface: '@movioza.slug_generator.cocur'
